language: php
php:
  - 5.6
services:
  - memcached
before_install: echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install
script:
  - vendor/bin/phpunit